# Generated by Django 6.0.6 on 2026-06-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('tipo', models.CharField(choices=[('disfraz', 'Consulta por disfraz'), ('stock', 'Disponibilidad'), ('personalizacion', 'Personalización'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo de consulta')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('respondida', models.BooleanField(default=False, verbose_name='Respondida')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Disfraz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(max_length=50)),
                ('tallas', models.CharField(help_text='Ej: S, M, L, XL', max_length=100)),
                ('stock', models.IntegerField(default=0)),
                ('comprados', models.IntegerField(default=0)),
                ('precio', models.IntegerField()),
                ('precio_anterior', models.IntegerField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='disfraces/')),
            ],
        ),
    ]
