# Generated by Django 6.0.6 on 2026-06-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disfraz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tallas', models.CharField(default='S, M, L, XL', max_length=200)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='disfraces/')),
            ],
        ),
    ]
